config/routes.rb
Bracket::Application.routes.draw do
  resources :tournament_brackets

  namespace :admin do
    resources :tournament_definitions
  end

end

app/models/score_criterium.rb
class ScoreCriterium < ActiveRecord::Base
  belongs_to :tournament_definition
  validates :name, :presence => true
  validates :weight, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 1 }
end

app/models/tournament_bracket.rb
class TournamentBracket < ActiveRecord::Base
end

app/models/tournament_definition.rb
class TournamentDefinition < ActiveRecord::Base
  has_friendly_id :name, :use_slug => true
  has_many :score_criteria, :dependent => :destroy

  validates :name, :presence => true
  validates :number_of_contestants, :quorum, :numericality => { :only_integer => true, :greater_than => 0}
  validates_associated :score_criteria

  accepts_nested_attributes_for :score_criteria, :allow_destroy => true
end

app/controllers/admin/tournament_definitions_controller.rb
class Admin::TournamentDefinitionsController < InheritedResources::Base
  layout Proc.new { |controller| controller.request.xhr? ? false : 'admin' }

  def create
    create! do
      return redirect_to admin_tournament_definitions_path
    end
  end

  def show
    redirect_to edit_admin_tournament_definition_path(resource)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tournament_brackets_controller.rb
class TournamentBracketsController < ApplicationController
  # GET /tournament_brackets
  # GET /tournament_brackets.xml
  def index
    @tournament_brackets = TournamentBracket.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tournament_brackets }
    end
  end

  # GET /tournament_brackets/1
  # GET /tournament_brackets/1.xml
  def show
    @tournament_bracket = TournamentBracket.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tournament_bracket }
    end
  end

  # GET /tournament_brackets/new
  # GET /tournament_brackets/new.xml
  def new
    @tournament_bracket = TournamentBracket.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tournament_bracket }
    end
  end

  # GET /tournament_brackets/1/edit
  def edit
    @tournament_bracket = TournamentBracket.find(params[:id])
  end

  # POST /tournament_brackets
  # POST /tournament_brackets.xml
  def create
    @tournament_bracket = TournamentBracket.new(params[:tournament_bracket])

    respond_to do |format|
      if @tournament_bracket.save
        format.html { redirect_to(@tournament_bracket, :notice => 'Tournament bracket was successfully created.') }
        format.xml  { render :xml => @tournament_bracket, :status => :created, :location => @tournament_bracket }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tournament_bracket.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tournament_brackets/1
  # PUT /tournament_brackets/1.xml
  def update
    @tournament_bracket = TournamentBracket.find(params[:id])

    respond_to do |format|
      if @tournament_bracket.update_attributes(params[:tournament_bracket])
        format.html { redirect_to(@tournament_bracket, :notice => 'Tournament bracket was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tournament_bracket.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tournament_brackets/1
  # DELETE /tournament_brackets/1.xml
  def destroy
    @tournament_bracket = TournamentBracket.find(params[:id])
    @tournament_bracket.destroy

    respond_to do |format|
      format.html { redirect_to(tournament_brackets_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/admin/tournament_definitions_helper.rb
module Admin::TournamentDefinitionsHelper
  def cancel_link
    text = @tournament_definition.new_record? ? 'Cancel' : 'Back'
    link_to text, admin_tournament_definitions_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tournament_brackets_helper.rb
module TournamentBracketsHelper
end

app/views/admin/tournament_definitions/_form.html.haml
%h3.title New Tournament Definition
= semantic_form_for [:admin, @tournament_definition] do |form|
  = form.inputs do
    = form.input :name
    = form.input :number_of_contestants, :required => true
    = form.input :quorum, :required => true
  #criteria
    %h4 Criteria
    %input#add_criteria{:type => :button, :value => "Add new criterium"}
    = form.inputs :for => :score_criteria do |c|
      = c.input :name
      = c.input :weight, :required => true
      %li.delete
        %a.delete_criteria{:href => '#'} Remove Criteria
  = form.buttons do
    = form.commit_button
    %li.cancel
      = cancel_link
#criteria_dup{:style => 'display: none;'}
  %fieldset.inputs.new
    %ol
      %li.string.required{:id => 'tournament_definition_score_criteria_attributes_%i_name_input'}
        %label{:for => "tournament_definition_score_criteria_attributes_%i_name"}
          Name
          %abbr{:title => :required} *
        %input{:type => 'text', 
          :maxlength => 255, 
          :id => 'tournament_definition_score_criteria_attributes_%i_name', 
          :name => 'tournament_definition[score_criteria_attributes][%i][name]'}
      %li.numeric.required{:id => 'tournament_definition_score_criteria_attributes_%i_weight_input'}
        %label{:for => "tournament_definition_score_criteria_attributes_%i_weight"}
          Weight
          %abbr{:title => :required} *
        %input{:type => 'text', 
          :maxlength => 255, 
          :id => 'tournament_definition_score_criteria_attributes_%i_weight', 
          :name => 'tournament_definition[score_criteria_attributes][%i][weight]'}
      %li.delete
        %a.delete_criteria{:href => '#'} Remove Criteria

app/views/admin/tournament_definitions/edit.html.haml
!= render :partial => 'form'

app/views/admin/tournament_definitions/index.html.haml
%h3 Tournament Definitions
= link_to "New Tournament Definition", new_admin_tournament_definition_url
- if @tournament_definitions.empty?
  %p No tournament definitions defined.
- else
  %table.tournament_definitions
    %thead
      %tr
        %th Name
        %th # Contestants
        %th Quorum
        %th # Criteria
        %th Actions
    %tbody
      - @tournament_definitions.each do |definition|
        %tr.tournament_definition
          %td
            = link_to definition.name, admin_tournament_definition_path(definition)
          %td= definition.number_of_contestants
          %td= definition.quorum
          %td= definition.score_criteria.count
          %td.actions
            = link_to "DELETE", admin_tournament_definition_path(definition), :confirm => "Are you sure you want to delete this definition?", :method => :delete

app/views/admin/tournament_definitions/new.html.haml
!= render :partial => 'form'

app/views/layouts/admin.html.haml
!!! 5
%html
  %head
    %title Bracket Admin
    != stylesheet_link_merged :base
    != javascript_include_merged :base, :admin
    != csrf_meta_tag
  %body

    = yield

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Bracket
    != stylesheet_link_merged :base
    != javascript_include_merged :base
    != csrf_meta_tag
  %body

    = yield

app/views/tournament_brackets/_form.html.erb
<%= form_for(@tournament_bracket) do |f| %>
  <% if @tournament_bracket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tournament_bracket.errors.count, "error") %> prohibited this tournament_bracket from being saved:</h2>

      <ul>
      <% @tournament_bracket.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tournament_brackets/edit.html.erb
<h1>Editing tournament_bracket</h1>

<%= render 'form' %>

<%= link_to 'Show', @tournament_bracket %> |
<%= link_to 'Back', tournament_brackets_path %>

app/views/tournament_brackets/index.html.erb
<h1>Listing tournament_brackets</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tournament_brackets.each do |tournament_bracket| %>
  <tr>
    <td><%= link_to 'Show', tournament_bracket %></td>
    <td><%= link_to 'Edit', edit_tournament_bracket_path(tournament_bracket) %></td>
    <td><%= link_to 'Destroy', tournament_bracket, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tournament bracket', new_tournament_bracket_path %>

app/views/tournament_brackets/new.html.erb
<h1>New tournament_bracket</h1>

<%= render 'form' %>

<%= link_to 'Back', tournament_brackets_path %>

app/views/tournament_brackets/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_tournament_bracket_path(@tournament_bracket) %> |
<%= link_to 'Back', tournament_brackets_path %>